### ISSUE TITLE
Gerätename & Räume abfragen

### ISSUE THREAD

**Issue by St0bsel** [Feller-AG/wiser-api#10]
Gibt es eine Möglichkeit, Loads anhanden des Namens abzufragen?

Ich habe die Namen und Räume im Gateway von der eSetup App migriert.
Das sieht dann grundsätzlich wie folgt aus:
![image](https://github.com/Feller-AG/wiser-api/assets/16537723/d4ea1887-34f0-4193-a9a5-446582f94b20)

Mir werden die entsprechenden Angaben via API aber über folgende Befehle nicht ausgegeben:
{{baseUrl}}/api/loads
{{baseUrl}}/api/loads/{{loadid}}

Hier sieht die Antwort wie folgt aus:
````json
{
    "data": {
        "id": 11,
        "unused": false,
        "name": "00014b23_1",
        "state": {
            "bri": 0,
            "flags": {
                "over_current": 0,
                "fading": 0,
                "noise": 0,
                "direction": 1,
                "over_temperature": 0
            }
        },
        "type": "dim",
        "device": "00014b23",
        "channel": 1,
        "sub_type": ""
    },
    "status": "success"
}
````

Auch die Räume werden nicht zurückgegeben:
{{baseUrl}}/api/rooms

Die Antwort sieht wie folgt aus:
````json
{
    "data": [],
    "status": "success"
}
````

Gibt es hier eine Möglichkeit, diese Bezeichnungen per API abzufragen?

**Comment by woodworm** [comment]
Um auf das API Zugriff zu bekommen, muss man mit `POST /api/account/claim` ein user-secret beziehen ([authentication](https://github.com/Feller-AG/wiser-tutorial/blob/main/doc/authentication.md)). Dadurch wird ein "Datentöpfli" erzeugt, indem alle durch den User erzeugten Daten gespeichert werden. Nun gibt es beim "Claimen" die Möglichkeit die Daten von einem bestehenden User zu übernehmen.
Wenn man die Daten z.B. vom Elektriker übernehmen möchte, muss man den Claim-Service wie folgt aufrufen:

```
POST /api/account/claim
{
  "user": "stubsel",
  "source": "installer"
}
```

**Comment by St0bsel** [comment]
Vielen Dank für deine Rückmeldung! Hat funktioniert.
![image](https://github.com/Feller-AG/wiser-api/assets/16537723/557df79c-f1d0-49bb-86c7-de692ff58ff1)
