### ISSUE TITLE
Detach a Job from SmartButton

### ISSUE THREAD

**Issue by grobotka** [Feller-AG/wiser-api#12]
Hi,

How can I detach a Job from the SmartButton?
The PATCH on api/smartbuttons/{id} with { "job": null } or {} does not work.

**Comment by grobotka** [comment]
Thanks, the empty job is exactly what I'm doing now.

**Comment by oliver-joos** [comment]
Ok! So I'm going to close this issue.
Feel free to open it again if you think it's necessary.
