### ISSUE TITLE
Stopping a moving motor load using the API

### ISSUE THREAD

**Issue by mpbzh** [Feller-AG/wiser-api#14]
When a motor load is moving, I can stop it by pressing a physical button. 

Is there an equivalent in the API? Sending the `target_state` with a value `{"moving": "stop"}` does not seem to be working. If I understand the API correctly, I can only send `level` or `tilt` values.

My workaround currently is sending a ctrl-event to simulate a button press.

**Comment by TimMayle** [comment]
Yes, you can.
Use the Put Command : 
/api/loads/{id}/ctrl  with the Stop button type.

**Comment by mpbzh** [comment]
I didn't realize there is a `stop` button type. That's exactly what I was looking for, thanks a lot!
