### ISSUE TITLE
Static IP for gateway ?

### ISSUE THREAD

**Issue by sulazix** [Feller-AG/wiser-api#8]
My router is on a timer, in the morning when I reconnect the gateway systematically receives a new IP address. 

Would it be possible to add a parameter for a fixed IP depending on the WLAN?

**Comment by oliver-joos** [comment]
No, a Feller µGateway does not support this. In principle, a network device should not request static IP, as this may lead to IP conflicts.

Instead, you can register a static IP address for a specific MAC address in your router. Open its web interface 192.168.x.1 via your browser and look for "Static IP Table" or similar.

**Comment by sulazix** [comment]
Thanks for your reply, I close the issue.
